name: PHPstan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Validate composer.json
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Install PHPStan
      run: composer require phpstan/phpstan --dev

    - name: PHPStan analyse
      run: vendor/bin/phpstan analyze src --level=max --no-progress
